import React from "react";
import { FaBehance, FaFacebook, FaLinkedin, FaTwitter } from "react-icons/fa";
export const links = [
	{
		id: 1,
		url: "/",
		text: "Home",
	},
	{
		id: 2,
		url: "/place-to-stay",
		text: "Place to stay",
	},
	{
		id: 3,
		url: "/projects",
		text: "NFTs",
	},
	{
		id: 4,
		url: "/contact",
		text: "Community",
	},
];

export const social = [
	{
		id: 1,
		url: "https://www.twitter.com",
		icon: <FaFacebook />,
	},
	{
		id: 2,
		url: "https://www.twitter.com",
		icon: <FaTwitter />,
	},
	{
		id: 3,
		url: "https://www.twitter.com",
		icon: <FaLinkedin />,
	},
	{
		id: 4,
		url: "https://www.twitter.com",
		icon: <FaBehance />,
	},
];

export const nftItems = [
	{
		id: 1,
		name: "Desert king",
		price: "1MBT per night",
		location: "2345km away",
		available: "available for 2weeks stay",
		stars: 2,
		image: "/images/cta1.png",
	},
	{
		id: 2,
		name: "Desert king",
		price: "1MBT per night",
		location: "2345km away",
		available: "available for 2weeks stay",
		stars: 2,
		image: "/images/cta2.png",
	},
	{
		id: 3,
		name: "Desert king",
		price: "1MBT per night",
		location: "2345km away",
		available: "available for 2weeks stay",
		stars: 2,
		image: "/images/cta3.png",
	},
	{
		id: 4,
		name: "Desert king",
		price: "1MBT per night",
		location: "2345km away",
		available: "available for 2weeks stay",
		stars: 2,
		image: "/images/cta4.png",
	},
	{
		id: 5,
		name: "Desert king",
		price: "1MBT per night",
		location: "2345km away",
		available: "available for 2weeks stay",
		stars: 2,
		image: "/images/cta5.png",
	},
	{
		id: 6,
		name: "Desert king",
		price: "1MBT per night",
		location: "2345km away",
		available: "available for 2weeks stay",
		stars: 2,
		image: "/images/cta6.png",
	},
	{
		id: 7,
		name: "Desert king",
		price: "1MBT per night",
		location: "2345km away",
		available: "available for 2weeks stay",
		stars: 2,
		image: "/images/cta7.png",
	},
	{
		id: 8,
		name: "Desert king",
		price: "1MBT per night",
		location: "2345km away",
		available: "available for 2weeks stay",
		stars: 2,
		image: "/images/ct8.png",
	},
];
export const PlaceToBeItems = [
	{
		id: 1,
		name: "Desert king",
		price: "1MBT per night",
		location: "2345km away",
		available: "available for 2weeks stay",
		stars: 2,
		image: "/images/ptb1.png",
	},
	{
		id: 2,
		name: "Desert king",
		price: "1MBT per night",
		location: "2345km away",
		available: "available for 2weeks stay",
		stars: 2,
		image: "/images/ptb2.png",
	},
	{
		id: 3,
		name: "Desert king",
		price: "1MBT per night",
		location: "2345km away",
		available: "available for 2weeks stay",
		stars: 2,
		image: "/images/ptb3.png",
	},
	{
		id: 4,
		name: "Desert king",
		price: "1MBT per night",
		location: "2345km away",
		available: "available for 2weeks stay",
		stars: 2,
		image: "/images/ptb4.png",
	},
	{
		id: 5,
		name: "Desert king",
		price: "1MBT per night",
		location: "2345km away",
		available: "available for 2weeks stay",
		stars: 2,
		image: "/images/ptb5.png",
	},
	{
		id: 6,
		name: "Desert king",
		price: "1MBT per night",
		location: "2345km away",
		available: "available for 2weeks stay",
		stars: 2,
		image: "/images/ptb6.png",
	},
	{
		id: 7,
		name: "Desert king",
		price: "1MBT per night",
		location: "2345km away",
		available: "available for 2weeks stay",
		stars: 2,
		image: "/images/ptb7.png",
	},
	{
		id: 8,
		name: "Desert king",
		price: "1MBT per night",
		location: "2345km away",
		available: "available for 2weeks stay",
		stars: 2,
		image: "/images/ptb8.png",
	},
	{
		id: 9,
		name: "Desert king",
		price: "1MBT per night",
		location: "2345km away",
		available: "available for 2weeks stay",
		stars: 2,
		image: "/images/ptb9.png",
	},
	{
		id: 10,
		name: "Desert king",
		price: "1MBT per night",
		location: "2345km away",
		available: "available for 2weeks stay",
		stars: 2,
		image: "/images/ptb10.png",
	},
	{
		id: 11,
		name: "Desert king",
		price: "1MBT per night",
		location: "2345km away",
		available: "available for 2weeks stay",
		stars: 2,
		image: "/images/ptb11.png",
	},
	{
		id: 12,
		name: "Desert king",
		price: "1MBT per night",
		location: "2345km away",
		available: "available for 2weeks stay",
		stars: 2,
		image: "/images/ptb12.png",
	},
	{
		id: 13,
		name: "Desert king",
		price: "1MBT per night",
		location: "2345km away",
		available: "available for 2weeks stay",
		stars: 2,
		image: "/images/ptb13.png",
	},
	{
		id: 14,
		name: "Desert king",
		price: "1MBT per night",
		location: "2345km away",
		available: "available for 2weeks stay",
		stars: 2,
		image: "/images/ptb14.png",
	},
	{
		id: 15,
		name: "Desert king",
		price: "1MBT per night",
		location: "2345km away",
		available: "available for 2weeks stay",
		stars: 2,
		image: "/images/ptb15.png",
	},
	{
		id: 16,
		name: "Desert king",
		price: "1MBT per night",
		location: "2345km away",
		available: "available for 2weeks stay",
		stars: 2,
		image: "/images/ptb16.png",
	},
];
